### ISSUE TITLE
Scenario description sometime unavailable

### ISSUE THREAD

**Issue by CorneliaAuerPIK** [SensesProject/gems#22]
![image](https://user-images.githubusercontent.com/29375193/75286306-988c1c80-5818-11ea-99bb-26e719c8806c.png)
It says only "storyline:"

**Comment by fidelthomet** [comment]
this is because what i get from the api is already formatted. Currently I only show an excerpt which worked quite well so far but apparently breaks here.

If i print everything it looks like this, which is ridiculous…
<img width="790" alt="image" src="https://user-images.githubusercontent.com/1699985/75336842-2523f280-588c-11ea-90f1-9be86b9a6b80.png">

So I think this needs to be changed either on the database side or we show everything but collapse the table cells that only the top two lines or so are visible at first… let me know what you tjhink

**Comment by fidelthomet** [comment]
also, for which scenarios and models should we provide metadata? For normal runs and reference, but not for funnels?
